# Generated by Django 3.2.8 on 2021-10-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='linkeding',
            new_name='linkedin',
        ),
    ]
