# Generated by Django 3.2.8 on 2021-10-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0002_rename_linkeding_perfil_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsTopicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=5000)),
                ('topico', models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('ae_pepresion', 'ANSIEDAD, ESTRÉS Y DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=20)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentirsebien.perfil')),
            ],
        ),
    ]
