# Generated by Django 3.2.8 on 2021-10-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0004_auto_20211019_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstopicos',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='itemstopicos',
            name='valor',
        ),
        migrations.AlterField(
            model_name='itemstopicos',
            name='item',
            field=models.TextField(max_length=2000),
        ),
    ]
