# Generated by Django 3.2.8 on 2021-10-19 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0005_auto_20211019_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentebienestar',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterModelOptions(
            name='itemstopicos',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterField(
            model_name='componentebienestar',
            name='topico',
            field=models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('ae_depresion', 'ANSIEDAD, ESTRÉS Y DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemstopicos',
            name='topico',
            field=models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('ae_depresion', 'ANSIEDAD, ESTRÉS Y DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=20),
        ),
        migrations.CreateModel(
            name='ResultadoPerfil',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('topico', models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('ae_depresion', 'ANSIEDAD, ESTRÉS Y DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=100)),
                ('puntaje', models.FloatField(default=0.0)),
                ('resultado', models.CharField(blank=True, max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentirsebien.perfil')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RespuestasPuente',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.SmallIntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentirsebien.itemstopicos')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentirsebien.perfil')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
