# Generated by Django 3.2.8 on 2021-10-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirsebien', '0006_auto_20211019_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstopicos',
            name='inverso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componentebienestar',
            name='topico',
            field=models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('das_ansiedad', 'ANSIEDAD'), ('das_estres', 'ESTRÉS'), ('das_depresion', 'DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemstopicos',
            name='topico',
            field=models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('das_ansiedad', 'ANSIEDAD'), ('das_estres', 'ESTRÉS'), ('das_depresion', 'DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resultadoperfil',
            name='topico',
            field=models.CharField(choices=[('sa_mental', 'SALUD MENTAL POSITIVA'), ('asertividad', 'ASERTIVIDAD'), ('das_ansiedad', 'ANSIEDAD'), ('das_estres', 'ESTRÉS'), ('das_depresion', 'DEPRESIÓN'), ('ap_social', 'APOYO SOCIAL'), ('vi_pareja', 'VIOLENCIA DE PAREJA')], max_length=100),
        ),
    ]
